[package]
name = "yyds-types"
version.workspace = true
edition.workspace = true
authors = ["Aster <192607617@qq.com>"]
description = "Core scripting runtime for YYDS"
publish = false
readme = "readme.md"
license = "MPL-2.0"
exclude = ["package.json", "tests/**"]

[lib]
path = "src/lib.rs"

[dependencies]

[dev-dependencies]

[features]
default = []

[package.metadata.docs.rs]
all-features = true
