[package]
name = "yyds-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Browser WebAssembly binding for the YYDS scripting runtime"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yyds-types = { workspace = true }
wasm-bindgen = { workspace = true }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
