/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Optional resource bounds for each schema or table scan. */
export interface SqliteReadLimits {
  /** Maximum b-tree and overflow pages visited. */
  maxPages?: number
  /** Maximum rows materialized. */
  maxRows?: number
  /** Maximum payload bytes per record. */
  maxPayloadBytes?: number
  /** Maximum total record payload bytes per scan. */
  maxTotalPayloadBytes?: number
}
/** The five SQLite schema columns, with SQL retained as opaque source. */
export interface SqliteSchemaObject {
  /** SQLite object type: table, index, view, or trigger. */
  kind: string
  /** Stored object name. */
  name: string
  /** Associated table or view name. */
  tableName: string
  /** Root page, absent for SQL NULL. */
  rootPage?: number
  /** CREATE source, absent for SQL NULL. */
  sql?: string
}
/** An undecoded SQLite table record with lossless rowid and binary payload. */
export interface SqliteTableRow {
  /** Exact signed 64-bit SQLite rowid. */
  rowid: bigint
  /** Record bytes after overflow assembly. */
  payload: Buffer
}
/** A SQLite query result value with its native storage class. */
export interface SqliteResultValue {
  /** SQLite storage class: null, integer, real, text, or blob. */
  kind: string
  /** Decimal signed integer when `kind` is integer. */
  integer?: string
  /** Floating point value when `kind` is real. */
  real?: number
  /** Text value when `kind` is text. */
  text?: string
  /** Lossless SQLite text bytes when the value is not valid UTF-8. */
  textBytes?: Buffer
  /** Binary value when `kind` is blob. */
  blob?: Buffer
}
/** Result of executing one SQLite statement. */
export interface SqliteQueryResult {
  /** Column labels in result order. */
  columns: Array<string>
  /** Rows with lossless integer and binary values. */
  rows: Array<Array<SqliteResultValue>>
  /** Changed row count. */
  changes: string
  /** Last insert rowid as exact signed decimal text. */
  lastInsertRowid: string
}
/** One SQLite bind parameter preserving its storage class and raw bytes. */
export interface SqliteParameter {
  /** SQLite storage class: null, integer, real, text, or blob. */
  kind: string
  /** Signed 64-bit integer as decimal text. */
  integer?: string
  /** Floating-point value. */
  real?: number
  /** Exact TEXT bytes, including non-UTF-8 data. */
  text?: Buffer
  /** Exact BLOB bytes. */
  blob?: Buffer
}
/** Library version (matches `yyds-types::version()`). */
export declare function yydsVersion(): string
/** Lightweight health probe for native binding smoke tests. */
export declare function ping(): string
/** Owned, read-only main-file bytes, independent of the YYDS cluster runtime. */
export declare class SqliteSnapshot {
  /** Copies a validated snapshot, bounded to 256 MiB unless overridden. */
  constructor(bytes: Buffer, maxSnapshotBytes?: number | undefined | null)
  /** Returns typed schema objects without parsing their SQL definitions. */
  schema(limits?: SqliteReadLimits | undefined | null): Array<SqliteSchemaObject>
  /** Reads raw records from an ordinary rowid table, not a SQL projection. */
  table(name: string, limits?: SqliteReadLimits | undefined | null): Array<SqliteTableRow>
}
/** A real SQLite connection backed by upstream SQLite, independent of YYDS storage. */
export declare class SqliteConnection {
  /** Opens or creates a SQLite file, or opens an existing file read-only when requested. */
  constructor(path: string, readOnly?: boolean | undefined | null)
  /** Executes one statement through the SQLite engine. */
  execute(sql: string): SqliteQueryResult
  /** Executes one statement with SQLite-native positional bind parameters. */
  executeWithParameters(sql: string, parameters: Array<SqliteParameter>): SqliteQueryResult
  /** Executes a multi-statement SQLite batch and discards result rows. */
  executeBatch(sql: string): void
  /** Starts an immediate write transaction. */
  beginImmediate(): void
  /** Commits the active transaction. */
  commit(): void
  /** Rolls back the active transaction. */
  rollback(): void
  /** Creates a named savepoint. */
  savepoint(name: string): void
  /** Releases a named savepoint. */
  releaseSavepoint(name: string): void
  /** Rolls back to a named savepoint without releasing it. */
  rollbackToSavepoint(name: string): void
  /** Reports whether the connection is outside a transaction. */
  isAutocommit(): boolean
  /** Reports the observed SQLite journal mode. */
  journalMode(): string
  /** Performs a passive WAL checkpoint. */
  checkpoint(): void
  /** Returns SQLite's native engine source id. */
  sourceId(): string
}
