/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Library version (matches `yyds-types::version()`). */
export declare function yydsVersion(): string
/** Lightweight health probe for native binding smoke tests. */
export declare function ping(): string
