/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Optional resource bounds for each schema or table scan. */
export interface SqliteReadLimits {
  /** Maximum b-tree and overflow pages visited. */
  maxPages?: number
  /** Maximum rows materialized. */
  maxRows?: number
  /** Maximum payload bytes per record. */
  maxPayloadBytes?: number
  /** Maximum total record payload bytes per scan. */
  maxTotalPayloadBytes?: number
}
/** The five SQLite schema columns, with SQL retained as opaque source. */
export interface SqliteSchemaObject {
  /** SQLite object type: table, index, view, or trigger. */
  kind: string
  /** Stored object name. */
  name: string
  /** Associated table or view name. */
  tableName: string
  /** Root page, absent for SQL NULL. */
  rootPage?: number
  /** CREATE source, absent for SQL NULL. */
  sql?: string
}
/** An undecoded SQLite table record with lossless rowid and binary payload. */
export interface SqliteTableRow {
  /** Exact signed 64-bit SQLite rowid. */
  rowid: bigint
  /** Record bytes after overflow assembly. */
  payload: Buffer
}
/** Library version (matches `yyds-types::version()`). */
export declare function yydsVersion(): string
/** Lightweight health probe for native binding smoke tests. */
export declare function ping(): string
/** Owned, read-only main-file bytes, independent of the YYDS cluster runtime. */
export declare class SqliteSnapshot {
  /** Copies a validated snapshot, bounded to 256 MiB unless overridden. */
  constructor(bytes: Buffer, maxSnapshotBytes?: number | undefined | null)
  /** Returns typed schema objects without parsing their SQL definitions. */
  schema(limits?: SqliteReadLimits | undefined | null): Array<SqliteSchemaObject>
  /** Reads raw records from an ordinary rowid table, not a SQL projection. */
  table(name: string, limits?: SqliteReadLimits | undefined | null): Array<SqliteTableRow>
}
